# Generated by Django 4.0.2 on 2022-02-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingweek',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='workingweek',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='workingweek',
            name='san',
        ),
        migrations.RemoveField(
            model_name='workingweek',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='workingweek',
            name='thu',
        ),
        migrations.RemoveField(
            model_name='workingweek',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='workingweek',
            name='wed',
        ),
        migrations.RemoveField(
            model_name='place',
            name='work_time',
        ),
        migrations.DeleteModel(
            name='WorkingDay',
        ),
        migrations.DeleteModel(
            name='WorkingWeek',
        ),
    ]
