# Generated by Django 4.0.2 on 2022-02-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_workingweek_workingday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingweek',
            name='place',
        ),
        migrations.DeleteModel(
            name='WorkingDay',
        ),
        migrations.DeleteModel(
            name='WorkingWeek',
        ),
    ]
