# Generated by Django 4.0.2 on 2022-02-26 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_workingday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='events.Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_place', to='events.image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='place_gallery', to='events.Image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_image', to='events.image'),
        ),
    ]
