# Generated by Django 4.0.2 on 2022-02-26 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_gallery_alter_event_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_time', to='events.place'),
        ),
    ]
